version: '3'
services:
  proxy:
    image: 'nginx:latest'
    ports:
      - '8090:80'
    networks:
      - note-network
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    hostname: proxy.notes.local
    container_name: main
  api:
    build: './api'
    volumes:
      - './api:/app'
    networks:
      - note-network
    hostname: api.notes.local
    container_name: api
  frontend:
    build: './frontend'
    ports:
      - '3000:3000'
    volumes:
      - './frontend/notes:/app'
    networks:
      - note-network
    hostname: frontend.notes.local
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
  database:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    networks:
      - note-network
    hostname: db.notes.local
    container_name: db
  wordpress:
    image: wordpress:latest
    networks:
      - note-network
    hostname: wp.notes.local
    container_name: wp
    volumes:
      - './wordpress:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
      STATIC_URL: 'http://static.notes.local'

  mariadb:
    image: mariadb:latest
    restart: always
    hostname: mariadb.notes.local
    container_name: mariadb
    networks:
      - note-network
    volumes:
      - './db_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
  static:
    image: 'nginx:latest'
    container_name: static
    ports:
      - '3213:80'
    networks:
      - note-network
    volumes:
      - './static/resources:/usr/share/nginx/html'
      - './static/nginx.conf:/etc/nginx/nginx.conf'
    hostname: static.notes.local
networks:
  note-network:
    driver: 'bridge'